crawler/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rssCrawl.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
)

management/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
                       url(r'^feeds/load', views.LoadFeedsView.as_view(), name='feed_load'),
                       url(r'^feeds/', views.FeedListView.as_view(), name='feed_list'),
                       url(r'^feeds/active/(?P<is_active>(True|False))/$',
                           views.FeedListView.as_view(),
                           name='feed_list'),
                       url(r'^channels/(?P<pk>\d+)/articles', views.ChannelArticleView.as_view(),
                           name='channel_articles'),
                       url(r'^channels/', views.ChannelListView.as_view(), name='channel_list'),
                       url(r'^home/', views.HomeView.as_view(), name='home')
)

rssCrawl/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from management.views import HomeView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^crawler/', include('crawler.urls', namespace='crawler')),
    url(r'^management/', include('management.urls', namespace='management')),
    url(r'^$', HomeView.as_view(), name='home'),
)

crawler/models.py
from django.db import models


class Setting(models.Model):
    is_active = models.BooleanField(default=True)
    data_path = models.CharField(max_length=250)


class Feed(models.Model):
    url = models.CharField(max_length=250)
    last_checked = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    etag = models.CharField(max_length=100)
    modified = models.CharField(max_length=100)


class RssObject(models.Model):
    title = models.CharField(max_length=250)
    link = models.CharField(max_length=250)
    description = models.TextField()

    published = models.DateTimeField(null=True, blank=True)
    author = models.CharField(max_length=50, null=True, blank=True)
    category = models.CharField(max_length=50, null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)


class Channel(RssObject):
    feed = models.OneToOneField(Feed)

    language = models.CharField(max_length=50, null=True, blank=True)
    copyright = models.CharField(max_length=50, null=True, blank=True)
    rating = models.CharField(max_length=150, null=True, blank=True)


class Item(RssObject):
    channel = models.ForeignKey(Channel)

    item_id = models.CharField(max_length=200, null=True, blank=True, unique=True)
    path_to_article = models.CharField(max_length=250)

management/models.py
from django.db import models

# Create your models here.

management/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()

crawler/views.py
from django.shortcuts import render

management/views.py
from django.shortcuts import render, redirect, render_to_response
from django.core.urlresolvers import reverse
from django.views.generic import ListView, View, TemplateView
from django.template import RequestContext

from .forms import UploadFileForm
from crawler.models import Feed, Channel
from crawler.tasks import *
from crawler import monster


class FilterActiveMixin(object):
    def get_queryset(self):
        queryset = super(FilterActiveMixin, self).get_queryset()
        is_active = self.kwargs.get('is_active')

        if is_active is None:
            return queryset
        is_active = is_active == 'True'
        return queryset.filter(is_active=bool(is_active))


class HomeView(TemplateView):
    template_name = 'management/home.html'


class FeedListView(FilterActiveMixin, ListView):
    paginate_by = 50
    model = Feed
    context_object_name = 'feeds'
    template_name = 'management/feeds/list.html'


class ChannelListView(ListView):
    paginate_by = 50
    model = Channel
    context_object_name = 'channels'
    template_name = 'management/channel/list.html'


class ChannelArticleView(View):
    def get(self, request, pk):
        channel = Channel.objects.filter(pk=pk).first()
        return render(request, 'management/channel/articles.html', {
            'articles': channel.item_set.all()
        })


class LoadFeedsView(View):
    def get(self, request):
        form = UploadFileForm()
        return render_to_response('management/feeds/load.html', {'form': form}, RequestContext(request))

    def post(self, request):
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            load_feeds(request.FILES['file'])
            return redirect(reverse('management:feed_list'))

        return render_to_response('management/feeds/load.html', {'form': form}, RequestContext(request))


def load_feeds(file):

    for line in file:
        url = line.replace('\n', '').replace('\r', '')
        if Feed.objects.filter(url=url).count() > 0:
            continue

        Feed.objects.create(url=url)

management/templates/management/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <script src="{% static 'management/js/jquery-1.11.0.min.js' %}"></script>
        <script src="{% static 'management/js/jquery.dajax.core.js' %}"></script>
        <script src="{% static 'management/js/spin.js' %}"></script>
        <script src="{% static 'management/js/custom.js' %}"></script>
        <script src="{% static 'management/bootstrap/3.1.1/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'management/bootstrap/bootbox/bootbox.min.js' %}"></script>
        <script src="{% static 'management/js/jquery.ba-serializeobject.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'management/bootstrap/3.1.1/css/bootstrap-theme.min.css' %}" />
        <link rel="stylesheet" href="{% static 'management/bootstrap/3.1.1/css/bootstrap.min.css' %}" />
        <title></title>
    </head>
    <body>
        <header id="top" class="navbar navbar-fixed-top navbar-inverse" role="banner">
             <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-target=".bs-navbar-collapse" data-toggle="collapse" type="button"></button>
                    <a href="{% url 'management:home' %}" class="navbar-brand">RSS Crawler</a>
                </div>
                <nav class="collapse navbar-collapse" role="navigation">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'management:feed_list' is_active=True %}">Feeds</a>
                        </li>
                        <li>
                            <a href="{% url 'management:channel_list' %}">Channels</a>
                        </li>
                    </ul>
                 </nav>

             </div>
        </header>
        <br />
        <br />
        <br />
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        {% block scripts %}{% endblock %}
    </body>
</html>

management/templates/management/channel/articles.html
{% extends 'management/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-10">
                    <h1 class="text-center">RSS Channel Articles</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Published</th>
                                <th>Link</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in articles %}
                            <tr>
                                <td>{{ object.pk }}</td>
                                <td>{{ object.title }}</td>
                                <td>{{ object.author }}</td>
                                <td>{{ object.published }}</td>
                                <td>{{ object.link }}</td></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% if is_paginated %}
            <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">Previous | </a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">| Next</a>
                        {% endif %}
                    </span>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

management/templates/management/channel/list.html
{% extends 'management/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-10">
                    <h1 class="text-center">RSS Channels</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Published</th>
                                <th>Link</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in channels %}
                            <tr>
                                <td>{{ object.pk }}</td>
                                <td>{{ object.title }}</td>
                                <td>{{ object.author }}</td>
                                <td>{{ object.published }}</td>
                                <td>{{ object.link }}</td>
                                <td><a class="btn btn-primary" href="{% url 'management:channel_articles' pk=object.pk %}">View</a>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% if is_paginated %}
            <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">Previous | </a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">| Next</a>
                        {% endif %}
                    </span>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

management/templates/management/feeds/list.html
{% extends 'management/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-10">
                    <h1 class="text-center">RSS Feeds</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Url</th>
                                <th>Is Active</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in feeds %}
                            <tr>
                                <td>{{ object.pk }}</td>
                                <td>{{ object.url }}</td>
                                <td>{{ object.is_active }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'management:feed_load' %}" class="btn-primary btn">Import feeds</a>
                </div>
            </div>
            {% if is_paginated %}
            <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">Previous | </a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">| Next</a>
                        {% endif %}
                    </span>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

management/templates/management/feeds/load.html
{% extends 'management/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <h1 class="text-center">Load a RSS feed file</h1>
            <br/>

            <div class="col-md-6 col-md-offset-3">
                <form method="POST" class="form-horizontal" role="form"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-3">
                            {{ form.file }}
                        </div>
                    </div>
                    <div class="col-sm-9 {% if form.errors %}has-error{% endif %}">
                        {% if form.errors %}
                            <label class="control-label" for="{{ form.auto_id }}">
                                {{ form.errors|striptags }}
                            </label>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-md-6">
                            <button type="submit" class="btn btn-primary btn-block"
                                    id="load-feed-btn">Load
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {

        });
    </script>
{% endblock %}

management/templates/management/home.html
{% extends 'management/base.html' %}

{% block content %}
<div class="container">
        <div class="jumbotron">
            <h1>RSS Crawler</h1>
            <p>
                RSS Crawler is a django app that focuses on querying RSS feeds and downloading articles they refer to.
                Celery Distributed Task Queue framework in junction with RabbitMQ broker and MySQL database enables horizontal scalability
                with a centralized control dashboard.

                <br />
                <br />
                This web interface display only basic information on processed feeds and is meant only as a proof of concept.

                <br />
                <br />

                A task can be scheduled via<a href="/admin/djcelery/periodictask/" class="btn btn-lg btn-link">scheduler</a>.

                <br />
                <br />

                A list of RSS feed urls can be imported via<a href="{% url 'management:feed_load' %}" class="btn btn-lg btn-link">importer</a>.
            </p>
            <p>
            </p>
        </div>
    </div>
{% endblock %}